# app/utils/category_config.py

SUB_CATEGORIES = [
    {"id": 6290, "name": "Engineering - Software"},
    {"id": 6283, "name": "Business/Systems Analysts"},
    {"id": 6287, "name": "Developers/Programmers"},
    {"id": 6291, "name": "Help Desk & IT Support"},
    {"id": 6293, "name": "Networks & Systems Administration"},
    {"id": 6286, "name": "Database Development & Administration"},
    {"id": 6301, "name": "Testing & Quality Assurance"},
    {"id": 6285, "name": "Consultants"},
    {"id": 6296, "name": "Sales - Pre & Post"},
    {"id": 6297, "name": "Security"},
    {"id": 6294, "name": "Product Management & Development"},
    {"id": 6292, "name": "Management"},
    {"id": 6289, "name": "Engineering - Network"},
    {"id": 6298, "name": "Team Leaders"},
    {"id": 6282, "name": "Architects"},
    {"id": 6302, "name": "Web Development & Production"},
    {"id": 6295, "name": "Programme & Project Management"},
    {"id": 6300, "name": "Telecommunications"},
    {"id": 6288, "name": "Engineering - Hardware"},
    {"id": 6284, "name": "Computer Operators"},
    {"id": 6299, "name": "Technical Writing"},
]

SUB_CATEGORY_NAME_TO_ID = {cat["name"]: cat["id"] for cat in SUB_CATEGORIES}
SUB_CATEGORY_NAMES = [cat["name"] for cat in SUB_CATEGORIES]

# specific keyword ต้องมาก่อน general เสมอ
KEYWORD_CATEGORY_MAP = [
    ("machine learning",       "Engineering - Software"),
    ("software engineer",      "Engineering - Software"),
    ("backend",                "Engineering - Software"),
    ("frontend",               "Engineering - Software"),
    ("fullstack",              "Engineering - Software"),
    ("full stack",             "Engineering - Software"),
    ("mobile developer",       "Engineering - Software"),
    ("flutter",                "Engineering - Software"),
    ("react native",           "Engineering - Software"),
    ("embedded",               "Engineering - Software"),
    ("web developer",          "Web Development & Production"),
    ("web designer",           "Web Development & Production"),
    ("dba",                    "Database Development & Administration"),
    ("database administrator", "Database Development & Administration"),
    ("data engineer",          "Database Development & Administration"),
    ("etl",                    "Database Development & Administration"),
    ("network engineer",       "Networks & Systems Administration"),
    ("devops",                 "Networks & Systems Administration"),
    ("sysadmin",               "Networks & Systems Administration"),
    ("cloud engineer",         "Networks & Systems Administration"),
    ("infrastructure",         "Networks & Systems Administration"),
    ("it support",             "Help Desk & IT Support"),
    ("help desk",              "Help Desk & IT Support"),
    ("helpdesk",               "Help Desk & IT Support"),
    ("technical support",      "Help Desk & IT Support"),
    ("qa engineer",            "Testing & Quality Assurance"),
    ("quality assurance",      "Testing & Quality Assurance"),
    ("tester",                 "Testing & Quality Assurance"),
    ("security engineer",      "Security"),
    ("cybersecurity",          "Security"),
    ("penetration",            "Security"),
    ("business analyst",       "Business/Systems Analysts"),
    ("system analyst",         "Business/Systems Analysts"),
    ("data analyst",           "Business/Systems Analysts"),
    ("data scientist",         "Business/Systems Analysts"),
    ("business intelligence",  "Business/Systems Analysts"),
    ("product manager",        "Product Management & Development"),
    ("product owner",          "Product Management & Development"),
    ("project manager",        "Programme & Project Management"),
    ("scrum master",           "Programme & Project Management"),
    ("it manager",             "Management"),
    ("engineering manager",    "Management"),
    ("head of",                "Management"),
    ("team lead",              "Team Leaders"),
    ("tech lead",              "Team Leaders"),
    ("solution architect",     "Architects"),
    ("software architect",     "Architects"),
    ("architect",              "Architects"),
    ("consultant",             "Consultants"),
    ("presales",               "Sales - Pre & Post"),
    ("sales engineer",         "Sales - Pre & Post"),
    ("account manager",        "Sales - Pre & Post"),
    ("telecom",                "Telecommunications"),
    ("hardware engineer",      "Engineering - Hardware"),
    ("firmware",               "Engineering - Hardware"),
    ("technical writer",       "Technical Writing"),
    # general fallback keywords (ต้องอยู่ท้ายสุด)
    ("developer",              "Developers/Programmers"),
    ("programmer",             "Developers/Programmers"),
    ("network",                "Engineering - Network"),
]